events {
    worker_connections 1024;
}

http {
    upstream php {
        server unix:/var/run/php-fpm.sock;
    }

    server {
        listen 80 default_server;
        server_name _;

        # Ruta correcta para tu proyecto Laminas
        root /var/www/html/app/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass php;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;

            # Temporal para ver errores de PHP
            fastcgi_param PHP_VALUE "display_errors=On\nerror_reporting=E_ALL";
        }

        location ~ /\.ht {
            deny all;
        }
    }
}